WebApp/ViewModels/EnergySupplierViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PmsEteck.ViewModels
{
    //TM
    public class EnergySupplierIndexViewModel
    {
        [Display(Name = "Sleutel")]
        public int iEnergySupplierID { get; set; }

        [Display(Name = "Energieleverancier")]
        public string sName { get; set; }

        [Display(Name = "Actief")]
        public bool bActive { get; set; }

        public int iMeterCount { get; set; }
    }

    public class EnergySupplierCreateViewModel
    {
        [Required]
        [Display(Name = "Naam")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "{0} moet tussen de {2} en {1} tekens bevatten")]
        public string sName { get; set; }
    }

    public class EnergySupplierEditViewModel
    {
        public int iEnergySupplierID { get; set; }

        [Required]
        [Display(Name = "Naam")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "{0} moet tussen de {2} en {1} tekens bevatten")]
        public string sName { get; set; }

        [Display(Name = "Actief")]
        public bool bActive { get; set; }
    }
}

WebApp/Controllers/EnergySupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PmsEteck.Data.Models;
using PmsEteck.ViewModels;
using WebApp.Data;
using X.PagedList;

namespace PmsEteck.Controllers
{
    //TM
    [Authorize]
    public class EnergySuppliersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EnergySuppliersController(ApplicationDbContext context)
        {
            _context = context;
        }

        //[Authorize(Roles = "EnergySuppliersViewer")]
        public ActionResult Index(string sorting, string searchValue = "", int page = 1)
        {
            IQueryable<EnergySupplierIndexViewModel> model = _context.EnergySuppliers
                .Where(w => string.IsNullOrEmpty(searchValue)
                || w.iEnergySupplierID.ToString().Contains(searchValue)
                || w.sName.Contains(searchValue))
                .Select(s => new EnergySupplierIndexViewModel
                {
                    iEnergySupplierID = s.iEnergySupplierID,
                    sName = s.sName,
                    bActive = s.bActive,
                    iMeterCount = _context.ConsumptionMeters
                        .Where(w => w.iEnergySupplierID == s.iEnergySupplierID).Count()
                });

            switch (sorting)
            {
                case "KeyAsc":
                    model = model.OrderBy(o => o.iEnergySupplierID);
                    break;
                case "KeyDesc":
                    model = model.OrderByDescending(o => o.iEnergySupplierID);
                    break;
                case "NameAsc":
                    model = model.OrderBy(o => o.sName);
                    break;
                case "NameDesc":
                    model = model.OrderByDescending(o => o.sName);
                    break;
                case "ActiveAsc":
                    model = model.OrderBy(o => o.bActive).ThenBy(t => t.iEnergySupplierID);
                    break;
                case "ActiveDesc":
                    model = model.OrderByDescending(o => o.bActive).ThenBy(t => t.iEnergySupplierID);
                    break;
                case "CountAsc":
                    model = model.OrderBy(o => o.iMeterCount);
                    break;
                case "CountDesc":
                    model = model.OrderByDescending(o => o.iMeterCount);
                    break;
                default:
                    model = model.OrderBy(o => o.iEnergySupplierID);
                    break;
            }

            IPagedList pagedListModel = model.ToPagedList(page, 25);

            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_EnergySupplierList", pagedListModel);

            return View(pagedListModel);
        }

        //[Authorize(Roles = "EnergySuppliersCreator")]
        public ViewResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "EnergySuppliersCreator")]
        public async Task<IActionResult> Create(EnergySupplierCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.EnergySuppliers.Add(new EnergySupplier
                {
                    sName = model.sName
                });

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        //[Authorize(Roles = "EnergySuppliersEditor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return BadRequest();

            EnergySupplier energySupplier = _context.EnergySuppliers.Find(id);

            if (energySupplier == null)
                return NotFound();

            EnergySupplierEditViewModel model = new EnergySupplierEditViewModel
            {
                iEnergySupplierID = energySupplier.iEnergySupplierID,
                sName = energySupplier.sName
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "EnergySuppliersEditor")]
        public async Task<IActionResult> Edit(EnergySupplierEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                EnergySupplier energySupplier = _context.EnergySuppliers.Find(model.iEnergySupplierID);
                energySupplier.sName = model.sName;

                _context.Entry(energySupplier).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
                //_context = null;
            }

            base.Dispose(disposing);
        }
    }
}

WebApp/Controllers/OperatorsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PmsEteck.Data.Models;
using WebApp.Data;
using WebApp.ViewModels;
using X.PagedList;

namespace WebApp.Controllers
{
    public class OperatorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OperatorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Operators
        public ActionResult Index(string sorting, string searchValue = "", int page = 1)
        {
            IQueryable<OperatorIndexViewModel> model = _context.Operators
                .Where(w => string.IsNullOrEmpty(searchValue)
                || w.iOperatorID.ToString().Contains(searchValue)
                || w.sName.Contains(searchValue))
                .Select(s => new OperatorIndexViewModel
                {
                    iOperatorID = s.iOperatorID,
                    sName = s.sName,
                    bActive = s.bActive,
                    iMeterCount = _context.ConsumptionMeters
                        .Where(w => w.iOperatorID == s.iOperatorID).Count()
                });

            switch (sorting)
            {
                case "KeyAsc":
                    model = model.OrderBy(o => o.iOperatorID);
                    break;
                case "KeyDesc":
                    model = model.OrderByDescending(o => o.iOperatorID);
                    break;
                case "NameAsc":
                    model = model.OrderBy(o => o.sName);
                    break;
                case "NameDesc":
                    model = model.OrderByDescending(o => o.sName);
                    break;
                case "ActiveAsc":
                    model = model.OrderBy(o => o.bActive).ThenBy(t => t.iOperatorID);
                    break;
                case "ActiveDesc":
                    model = model.OrderByDescending(o => o.bActive).ThenBy(t => t.iOperatorID);
                    break;
                case "CountAsc":
                    model = model.OrderBy(o => o.iMeterCount);
                    break;
                case "CountDesc":
                    model = model.OrderByDescending(o => o.iMeterCount);
                    break;
                default:
                    model = model.OrderBy(o => o.iOperatorID);
                    break;
            }

            IPagedList pagedListModel = model.ToPagedList(page, 25);

            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_OperatorList", pagedListModel);

            return View(pagedListModel);
        }

        // GET: Operators/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Operators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("iOperatorID,sName,bActive")] Operator @operator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@operator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@operator);
        }

        [Authorize(Roles = "OperatorsEditor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Operator Operator = await _context.Operators.FindAsync(id);

            if (Operator == null)
                return NotFound();

            OperatorEditViewModel model = new OperatorEditViewModel
            {
                iOperatorID = Operator.iOperatorID,
                sName = Operator.sName
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "OperatorsEditor")]
        public async Task<IActionResult> Edit(OperatorEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Operator Operator = await _context.Operators.FindAsync(model.iOperatorID);
                Operator.sName = model.sName;

                try
                {
                    _context.Update(Operator);
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if (!OperatorExists(Operator.iOperatorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        private bool OperatorExists(int id)
        {
            return _context.Operators.Any(e => e.iOperatorID == id);
        }
    }
}

WebApp/Views/EnergySuppliers/Create.cshtml
@model PmsEteck.ViewModels.EnergySupplierCreateViewModel

@{
    ViewBag.Title = "Energieleverancier toevoegen";
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("Index", "Operators")">Alle energieleveranciers</a></li>
    <li class="active">@ViewBag.Title</li>
</ol>

<h2 class="page-header">@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.sName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-4">
                <a href="@Url.Action("Index")" class="btn btn-default pull-right">
                    <span class="fa fa-arrow-left"></span>
                    Terug
                </a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-block btn-primary">
                    <span class="fa fa-save"></span>
                    Opslaan
                </button>
            </div>
        </div>
    </div>
}

WebApp/Views/EnergySuppliers/Edit.cshtml
@model PmsEteck.ViewModels.EnergySupplierEditViewModel

@{
    ViewBag.Title = "Energieleverancier bewerken";
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("Index", "EnergySuppliers")">Alle energieleveranciers</a></li>
    <li class="active">@Model.sName bewerken</li>
</ol>

<h2 class="page-header">@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(h => h.iEnergySupplierID)
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.sName, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.sName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4">
                <a href="@Url.Action("Index")" class="btn btn-default pull-right">
                    <span class="fa fa-arrow-left"></span>
                    Terug
                </a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-block btn-primary">
                    <span class="fa fa-save"></span>
                    Opslaan
                </button>
            </div>
        </div>
    </div>
}

WebApp/Views/EnergySuppliers/Index.cshtml
@model IEnumerable<PmsEteck.ViewModels.EnergySupplierIndexViewModel>

@{
    ViewBag.Title = "Alle energieleveranciers";
}

<ol class="breadcrumb">
    <li class="active">@ViewBag.Title</li>
</ol>

<h2 class="page-header">@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "EnergySuppliers", FormMethod.Get, new { data_pmseteck_ajax = "true", data_pmseteck_target = "#energySuppliersList", @class = "form-inline" }))
{
    <div class="form-group">
        @if (User.IsInRole("EnergySuppliersCreator"))
        {
            <a href="@Url.Action("Create")" class="btn btn-primary">
                <span class="fa fa-plus"></span>
                Nieuwe energieleverancier
            </a>
        }
    </div>
    <div class="form-group pull-right">
        <div class="input-group">
            @Html.TextBox("searchValue", null, null, new { placeholder = "Zoeken...", @class = "form-control", autofocus = "autofocus" })
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
        </div>
    </div>
}

@await Html.PartialAsync("_EnergySupplierList", Model)

WebApp/Views/EnergySuppliers/_EnergySupplierList.cshtml
@model X.PagedList.PagedList<PmsEteck.ViewModels.EnergySupplierIndexViewModel>
@using X.PagedList.Mvc.Core

<div id="energySuppliersList" class="indexlist" data-pmseteck-target="#energySuppliersList">
    <table class="table table-hover">
        <thead class="tableheader">
            <tr>
                <th>
                    @Html.ActionLink("Sleutel", "Index", new { sorting = Context.Request.Query["sorting"] == "KeyAsc" ? "KeyDesc" : "KeyAsc" })
                    @if (Context.Request.Query["sorting"] == "KeyAsc")
                    {<span class="fa fa-chevron-down"></span>}
                    else if (Context.Request.Query["sorting"] == "KeyDesc")
                    { <span class="fa fa-chevron-up"></span>}
                </th>
                <th>
                    @Html.ActionLink("Naam", "Index", new { sorting = Context.Request.Query["sorting"] == "NameAsc" ? "NameDesc" : "NameAsc" })
                    @if (Context.Request.Query["sorting"] == "NameAsc")
                    {<span class="fa fa-chevron-down"></span>}
                    else if (Context.Request.Query["sorting"] == "NameDesc")
                    { <span class="fa fa-chevron-up"></span>}
                </th>
                <th class="text-center">
                    @Html.ActionLink("Actief", "Index", new { sorting = Context.Request.Query["sorting"] == "ActiveAsc" ? "ActiveDesc" : "ActiveAsc" })
                    @if (Context.Request.Query["sorting"] == "ActiveAsc")
                    {<span class="fa fa-chevron-down"></span>}
                    else if (Context.Request.Query["sorting"] == "ActiveDesc")
                    { <span class="fa fa-chevron-up"></span>}
                </th>
                <th class="text-center">
                    @Html.ActionLink("Aantal meters", "Index", new { sorting = Context.Request.Query["sorting"] == "CountAsc" ? "CountDesc" : "CountAsc" })
                    @if (Context.Request.Query["sorting"] == "CountAsc")
                    {<span class="fa fa-chevron-down"></span>}
                    else if (Context.Request.Query["sorting"] == "CountDesc")
                    { <span class="fa fa-chevron-up"></span>}
                </th>
                @if (User.IsInRole("EnergySuppliersEditor"))
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var energySupplier in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => energySupplier.iEnergySupplierID)
                    </td>
                    <td>
                        @Html.DisplayFor(model => energySupplier.sName)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(model => energySupplier.bActive)
                    </td>
                    <td class="text-center">
                        @if (User.IsInRole("ConsumptionMetersViewer"))
                        {
                            <a href="@Url.Action("ConsumptionMeters", "EnergySuppliers", new { id = energySupplier.iEnergySupplierID })">@Html.DisplayFor(model => energySupplier.iMeterCount)</a>
                        }
                        else
                        {
                            @Html.DisplayFor(model => energySupplier.iMeterCount)
                        }
                    </td>
                    @if (User.IsInRole("EnergySuppliersEditor"))
                    {
                        <td class="text-right">
                            @using (Html.BeginForm("Lock", "EnergySuppliers", new { id = energySupplier.iEnergySupplierID }, FormMethod.Post))
                            {
                                <a href="@Url.Action("Edit", new { id = energySupplier.iEnergySupplierID })" class="btn btn-xs btn-warning">
                                    <span class="fa fa-pencil"></span>
                                </a>
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-xs btn-@(energySupplier.bActive ? "danger" : "success")">
                                    <span class="fa fa-@(energySupplier.bActive ? "" : "un")lock"></span>
                                    @(energySupplier.bActive ? "vergrendel" : "ontgrendel")
                                </button>
                            }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
    @Model.FirstItemOnPage - @Model.LastItemOnPage van @Model.TotalItemCount
    @if (Model.PageCount > 1)
    {
        <div class="pagedList">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sorting = Context.Request.Query["sorting"] }))//, new PagedListRenderOptions { LinkToNextPageFormat = "<span class='glyphicon glyphicon-triangle-right'></span>", LinkToPreviousPageFormat = "<span class='glyphicon glyphicon-triangle-left'></span>", LinkToFirstPageFormat = "<span class='glyphicon glyphicon-fast-backward'></span>", LinkToLastPageFormat = "<span class='glyphicon glyphicon-fast-forward'></span>", MaximumPageNumbersToDisplay = 5 })
        </div>
    }
</div>