WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using PmsEteck.Data.Models;
using PmsEteck.Helpers;
using WebApp.Data;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public AdminController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailSender emailSender,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _context = context;
        }
        //[Authorize(Roles="UserManager")]
        public async Task<IActionResult> Index(string searchValue, string sorting = null, int page = 1)
        {
            IQueryable<AccountListViewModel> accountList = _userManager.Users
                                                                    .Where(w =>
                                                                        string.IsNullOrEmpty(searchValue) ||
                                                                        w.Email.ToUpper().Contains(searchValue.ToUpper()) ||
                                                                        w.sFirstName.ToUpper().Contains(searchValue.ToUpper()) ||
                                                                        w.sLastName.ToUpper().Contains(searchValue.ToUpper())
                                                                    )
                                                                    .Select(s => new AccountListViewModel
                                                                    {
                                                                        Id = s.Id,
                                                                        Email = s.Email,
                                                                        sFirstName = s.sFirstName,
                                                                        sLastName = s.sLastName,
                                                                        EmailConfirmed = s.EmailConfirmed
                                                                    });
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_UserList", await accountList.ToListAsync());

            return View(await accountList.ToListAsync());
        }

        // GET: /Admin/Register
        //[Authorize(Roles = "UserManager")]
        public ActionResult Register()
        {
            var model = new RegisterViewModel()
            {
                MaintenanceContactList = new SelectList(_context.MaintenanceContacts.OrderBy(o => o.sOrganisation).Select(s => new SelectListItem { Value = s.iMaintenanceContactKey.ToString(), Text = s.sOrganisation + " (" + s.iMaintenanceContactKey + ")" }), "Value", "Text")
            };
            return View(model);
        }

        // POST: /Admin/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "UserManager")]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var secretKey = Password.Generate(40, 0);
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email, sFirstName = model.sFirstName, sLastName = model.sLastName, IsDuoAuthenticatorEnabled = true, DuoAuthenticatorSecretKey = secretKey, MaintenanceContactID = model.MaintenanceContactID };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    await _userManager.SetTwoFactorEnabledAsync(user, true);

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    string code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebUtility.UrlEncode(code);
                    var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Url.ActionContext.HttpContext.Request.Scheme);
                    string body = string.Format("<div>&nbsp;</div>" +
                        "<div><p>Beste {0},</p>" +
                        "<p>Er is een account aangemaakt voor toegang tot het Project Management Systeem van Eteck.</p>" +
                        "<p>Om toegang te krijgen tot het systeem is het noodzakelijk om je emailadres te verifiëren. Dit kun je doen doormiddel van onderstaande link.</p>" +
                        "</div><div>&nbsp;</div>" +
                        "<div><p>" +
                        "<a href=\"" + callbackUrl + "\" style=\"color: #fff; text-decoration: none; background-color: rgb(28, 132, 198);text-align: center; vertical-align: middle;cursor: pointer;padding: 6px 12px; border-radius: 4px;;line-height: 1.42857143;\">Emailadres verifiëren</a>" +
                        "</p></div>" +
                        "<div>&nbsp;</div>" +
                        "<div><p>Na het verifiëren van het emailadres kan direct een wachtwoord ingesteld worden.</p><p>Groeten,<br> Het Eteck Team</p></div>", user.FullName);
                    await _emailSender.SendEmailAsync(user.Email, "Emailadres bevestigen", body);

                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }
            model.MaintenanceContactList = new SelectList(_context.MaintenanceContacts.OrderBy(o => o.sOrganisation).Select(s => new SelectListItem { Value = s.iMaintenanceContactKey.ToString(), Text = s.sOrganisation + " (" + s.iMaintenanceContactKey + ")" }), "Value", "Text");
            return View(model);
        }

        // GET: /Admin/ManagerRoleGroups/5
        //[Authorize(Roles = "UserManager")]
        public async Task<ActionResult> ManageRoleGroups(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            ApplicationUser user = await _userManager.FindByIdAsync(id);

            if (user == null)
                return NotFound();

            var model = new AccountRoleGroupViewModel
            {
                Id = user.Id,
                SelectedGroups = await _context.ApplicationUserRoleGroup.Where(c => c.UserId == user.Id).Select(c => c.RoleGroup.Name).ToListAsync(),
                RoleGroups = _context.RoleGroups.OrderBy(o => o.Name)
                                        .Select(s => new SelectListItem
                                        {
                                            Text = s.Name,
                                            Value = s.Name
                                        })
                                        .ToList()
                                                     
            };
            
            return View(model);
        }
        
        //POST: /Admin/ManageUserGroups/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "UserManager")]
        public async Task<ActionResult> ManageRoleGroups(AccountRoleGroupViewModel model, string id)
        {
            if (string.IsNullOrEmpty(id))
                ModelState.AddModelError(string.Empty, "Geen geldige aanvraag.");

            ApplicationUser user = await _context.Users.Include(u => u.RoleGroups).ThenInclude(x => x.RoleGroup).FirstOrDefaultAsync(f => f.Id == id);
            
            if (user == null)
                ModelState.AddModelError(string.Empty, "De ingestuurde gebruiker kan niet gevonden worden");

            if (ModelState.IsValid)
            {
                IQueryable<RoleGroup> roleGroupList = _context.RoleGroups.Include(i => i.Roles).ThenInclude(a => a.ApplicationRole).AsQueryable();

                if (model.SelectedGroups != null)
                {
                    var test = model.SelectedGroups;
                    var selectedRoleGroups = roleGroupList.Where(w => model.SelectedGroups.Contains(w.Name));
                    HashSet<int> selectedRoleIds = new HashSet<int>(roleGroupList.Where(w => model.SelectedGroups.Contains(w.Name)).Select(s => s.Id));
                    var userRoleGroups = user.RoleGroups;
                    HashSet<int> userRoleGroupIds = new HashSet<int>(user.RoleGroups.Select(s => s.RoleGroup.Id));

                    HashSet<string> roleNameList = new HashSet<string>(await _context.ApplicationUserRoleGroup.Where(c => c.UserId == user.Id).Select(c => c.RoleGroup.Name).ToListAsync());
                        //user.RoleGroups.SelectMany(sm => sm.RoleGroup.Roles).Select(s => s.RoleGroup.Name));

                    // What to do with new selected rolegroups
                    foreach (var roleGroup in selectedRoleGroups.Where(w => !userRoleGroupIds.Contains(w.Id)).ToList())
                    {
                        bool roleGroupHasError = false;
                        foreach (var applicationRole in roleGroup.Roles)
                        {

WebApp/Controllers/OperatorsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PmsEteck.Data.Models;
using WebApp.Data;
using WebApp.ViewModels;
using X.PagedList;

namespace WebApp.Controllers
{
    public class OperatorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OperatorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Operators
        public ActionResult Index(string sorting, string searchValue = "", int page = 1)
        {
            IQueryable<OperatorIndexViewModel> model = _context.Operators
                .Where(w => string.IsNullOrEmpty(searchValue)
                || w.iOperatorID.ToString().Contains(searchValue)
                || w.sName.Contains(searchValue))
                .Select(s => new OperatorIndexViewModel
                {
                    iOperatorID = s.iOperatorID,
                    sName = s.sName,
                    bActive = s.bActive,
                    iMeterCount = _context.ConsumptionMeters
                        .Where(w => w.iOperatorID == s.iOperatorID).Count()
                });

            switch (sorting)
            {
                case "KeyAsc":
                    model = model.OrderBy(o => o.iOperatorID);
                    break;
                case "KeyDesc":
                    model = model.OrderByDescending(o => o.iOperatorID);
                    break;
                case "NameAsc":
                    model = model.OrderBy(o => o.sName);
                    break;
                case "NameDesc":
                    model = model.OrderByDescending(o => o.sName);
                    break;
                case "ActiveAsc":
                    model = model.OrderBy(o => o.bActive).ThenBy(t => t.iOperatorID);
                    break;
                case "ActiveDesc":
                    model = model.OrderByDescending(o => o.bActive).ThenBy(t => t.iOperatorID);
                    break;
                case "CountAsc":
                    model = model.OrderBy(o => o.iMeterCount);
                    break;
                case "CountDesc":
                    model = model.OrderByDescending(o => o.iMeterCount);
                    break;
                default:
                    model = model.OrderBy(o => o.iOperatorID);
                    break;
            }

            IPagedList pagedListModel = model.ToPagedList(page, 25);

            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_OperatorList", pagedListModel);

            return View(pagedListModel);
        }

        // GET: Operators/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Operators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("iOperatorID,sName,bActive")] Operator @operator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@operator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@operator);
        }

        [Authorize(Roles = "OperatorsEditor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Operator Operator = await _context.Operators.FindAsync(id);

            if (Operator == null)
                return NotFound();

            OperatorEditViewModel model = new OperatorEditViewModel
            {
                iOperatorID = Operator.iOperatorID,
                sName = Operator.sName
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "OperatorsEditor")]
        public async Task<IActionResult> Edit(OperatorEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Operator Operator = await _context.Operators.FindAsync(model.iOperatorID);
                Operator.sName = model.sName;

                try
                {
                    _context.Update(Operator);
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if (!OperatorExists(Operator.iOperatorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        private bool OperatorExists(int id)
        {
            return _context.Operators.Any(e => e.iOperatorID == id);
        }
    }
}

WebApp/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html lang="nl">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <environment include="Development">
        <script src="~/Scripts/modernizr-*"></script>
        <link rel="stylesheet" href="~/Content/css" />
    </environment>

    <environment include="Develpment">
        <script src="~/Scripts/jquery-{version}.js"></script>
        <script src="~/Scripts/jquery.unobtrusive*"></script>
        <script src="~/Scripts/autoNumeric/*.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    </environment>
    <environment include="Develpment">
        <script src="~/Scripts/application.js"></script>
        <script src="~/Scripts/knockout*"></script>
        <script src="~/Scripts/jquery-ui-{version}.js"></script>
    </environment>

    <environment include="Development">
        <link rel="stylesheet" href="~/Content/bootstrap-datepicker3.css" />
        <link rel="stylesheet" href="~/Content/bootstrap-timeline.css" />
        <link rel="stylesheet" href="~/Content/bootstrap.css" />
        <link rel="stylesheet" href="~/Content/bootstrap-theme.css" />
        <link rel="stylesheet" href="~/Content/bootstrap-select.css" />
        <link rel="stylesheet" href="~/Content/bootstrap-tagsinput.css"/>
        <link rel="stylesheet" href="~/Content/font-awesome.css" />
        <link rel="stylesheet" href="~/Content/style.css" />
    </environment>


    <environment include="Development">
        <script src="wwwroot/Scripts/bundle.js"></script>
    </environment>

    <!--EUUUU-->
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
</head>
<body class="container-fluid backgroundpage">
    <div class="row">
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 col-lg-offset-4 col-lg-4">
            @RenderBody()
        </div>
    </div>
    <environment include="Development">
        <script src="wwwroot/Scripts/BootstrapBundle.js"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_NavbarPartial.cshtml
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a href="/" class="navbar-brand">
        <img src="~/Images/Eteck_nieuw.png" />
    </a>
</div>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Netbeheerders", "Index", "Operators")</li>
        @if (User.IsInRole("ServiceTicketsViewer") || User.IsInRole("ServiceInvoiceLinesViewer"))
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Service & Onderhoud
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @if (User.IsInRole("ServiceTicketsViewer"))
                    {
                        <li>@Html.ActionLink("Servicemeldingen", "Index", "ServiceTickets")</li>
                    }
                    @if (User.IsInRole("ServiceInvoiceLinesViewer"))
                    {
                        <li>@Html.ActionLink("Factuurregels", "Index", "ServiceInvoiceLines")</li>
                    }
                </ul>
            </li>

        }
        @if (User.IsInRole("OpportunitiesViewer"))
        {

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Pipeline
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Pipeline", "Index", "Opportunities")</li>
                    @if (User.IsInRole("InstallationPartnersViewer"))
                    {
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Intallatiepartners", "Index", "InstallationPartners")</li>
                    }
                </ul>
            </li>
        }
        @if (User.IsInRole("BudgetsViewer") || User.IsInRole("DashboardFinancialManagementViewer"))
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Financieel management
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @if (User.IsInRole("DashboardFinancialManagementViewer"))
                    {
                        <li>@Html.ActionLink("Overzicht", "FinancialManagement", "Dashboard")</li>
                        <li role="separator" class="divider"></li>
                    }
                    @if (User.IsInRole("BudgetsViewer"))
                    {
                        <li>@Html.ActionLink("Begrotingen", "Index", "Budgets")</li>
                    }
                </ul>
            </li>

        }
        @if (User.IsInRole("CustomersViewer"))
        {
            <li>@Html.ActionLink("Entiteiten", "Index", "Customers")</li>
        }
        @if (User.IsInRole("MaintenanceContactsViewer") && User.IsInRole("ProjectsViewer"))
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Project management
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Projecten", "Index", "Projects")</li>
                    <li role="separator" class="divider"></li>
                    <li>@Html.ActionLink("Onderhoudspartijen", "Index", "MaintenanceContacts")</li>
                </ul>
            </li>
        }
        else if (User.IsInRole("ProjectsViewer"))
        {
            <li>@Html.ActionLink("Projecten", "Index", "Projects")</li>
        }
        @if (User.IsInRole("AddressesViewer"))
        {
            <li>@Html.ActionLink("Aansluitingen", "Index", "Addresses")</li>
        }
        @if (User.IsInRole("ConsumptionMetersViewer") || User.IsInRole("ReportViewer"))
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Energetisch management
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @if (User.IsInRole("ReportViewer"))
                    {
                        <li>@Html.ActionLink("EM Rapportage", "IndexAsync", "Report")</li>
                    }
                    @if (User.IsInRole("ServiceViewer"))
                    {
                        <li>@Html.ActionLink("Services", "Index", "Service")</li>
                    }
                    @if (User.IsInRole("ConsumptionMeterSuppliersViewer"))
                    {
                        <li>@Html.ActionLink("Leveranciers", "Index", "ConsumptionMeterSuppliers")</li>
                    }
                    @if (User.IsInRole("DefaultsViewer"))
                    {
                        <li>@Html.ActionLink("Energiestandaarden", "Index", "Defaults")</li>
                    }
                    <li role="separator" class="divider"></li>
                    @if (User.IsInRole("ConsumptionMetersViewer"))
                    {
                        <li>@Html.ActionLink("Meters", "Index", "ConsumptionMeters")</li>
                    }
                    @if (User.IsInRole("MeterChangeLogsViewer"))
                    {
                        <li>@Html.ActionLink("Meterwissels", "Index", "MeterChangeLogs")</li>
                    }
                    @if (User.IsInRole("CountersViewer"))
                    {
                        <li>@Html.ActionLink("Telwerken", "Index", "Counters")</li>
                    }
                    @if (User.IsInRole("RateCardsViewer"))
                    {
                        <li>@Html.ActionLink("Tariefkaarten", "Index", "RateCards")</li>
                    }
                    @if (User.IsInRole("RateCardScalesViewer"))
                    {
                        <li>@Html.ActionLink("Tariefkaartstaffels", "Index", "RateCardScales")</li>
                    }
                    <li role="separator" class="divider"></li>
                    @if (User.IsInRole("EnergySuppliersViewer"))
                    {
                        <li>@Html.ActionLink("Energieleveranciers", "Index", "EnergySuppliers")</li>
                    }
                    @if (User.IsInRole("OperatorsViewer"))
                    {
                        <li>@Html.ActionLink("Netbeheerders", "Index", "Operators")</li>
                    }
                    @if (User.IsInRole("MeasuringOfficersViewer"))
                    {
                        <li>@Html.ActionLink("Meetverantwoordelijke", "Index", "MeasuringOfficers")</li>
                    }
                    <li role="separator" class="divider"></li>
                    @if (User.IsInRole("ConnectionTypesViewer"))
                    {
                        <li>@Html.ActionLink("Aansluittypen", "Index", "ConnectionTypes")</li>
                    }
                    @if (User.IsInRole("ConsumptionMeterTypesViewer"))
                    {
                        <li>@Html.ActionLink("Metertypen", "Index", "ConsumptionMeterTypes")</li>
                    }
                    @if (User.IsInRole("CounterTypesViewer"))
                    {
                        <li>@Html.ActionLink("Telwerktypen", "Index", "CounterTypes")</li>
                    }
                    @if (User.IsInRole("UnitsViewer"))
                    {
                        <li>@Html.ActionLink("Eenheden", "Index", "Units")</li>
                    }
                    @if (User.IsInRole("CounterTypesViewer"))
                    {
                        <li>@Html.ActionLink("Ophaalfrequenties", "Index", "Frequencies")</li>
                    }

                    @if (User.IsInRole("ReportValidationSetsViewer"))
                    {
                        <li>@Html.ActionLink("Validatieprofielen", "Index", "ReportValidationSets")</li>
                    }
                    @if (User.IsInRole("SeasonalPatternsViewer"))
                    {
                        <li>@Html.ActionLink("Seizoenspatronen", "Index", "SeasonalPatterns")</li>

                    }
                    @if (User.IsInRole("CountersViewer"))
                    {
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Ongevalideerde verbruiken", "UnvalidatedConsumptions", "Consumptions")</li>
                    }
                </ul>
            </li>
        }
        @if (User.IsInRole("DebtorsViewer") || User.IsInRole("OccupantsViewer") || User.IsInRole("InvoiceBatchesViewer") || User.IsInRole("TicketReviewsViewer"))
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Klantzaken
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @if (User.IsInRole("DashboardCustomerManagementViewer"))
                    {
                        <li>@Html.ActionLink("Dashboard", "CustomerManagement", "Dashboard")</li>
                    }
                    @if (User.IsInRole("TicketReviewsViewer"))
                    {
                        <li>@Html.ActionLink("Reviews", "Index", "TicketReviews")</li>
                    }
                    <li role="separator" class="divider"></li>
                    @if (User.IsInRole("DebtorsViewer"))
                    {
                        <li>@Html.ActionLink("Debiteuren", "Index", "Debtors")</li>
                    }
                    @if (User.IsInRole("OccupantsViewer"))
                    {
                        <li>@Html.ActionLink("Bewoners", "Index", "Occupants")</li>
                    }
                    @if (User.IsInRole("InvoiceBatchesViewer"))
                    {
                        <li>@Html.ActionLink("Facturatie", "Index", "InvoiceBatches")</li>
                        <li>@Html.ActionLink("Facturatie (nieuw)", "IndexNew", "InvoiceBatches")</li>
                    }
                    @if (User.IsInRole("TicketsViewer"))
                    {
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Meldingen", "Index", "Tickets")</li>
                        <li>@Html.ActionLink("Nieuwe meldingen", "Queue", "Tickets")</li>
                    }
                    @if (User.IsInRole("UnvalidatedConsumptionsViewer"))
                    {
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Ongevalideerde standen", "Index", "UnvalidatedConsumptions")</li>
                    }
                </ul>
            </li>
        }
        @if (User.IsInRole("UserManager"))
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    App beheer
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @if (User.IsInRole("UserManager"))
                    {
                        <li>@Html.ActionLink("Gebruikersbeheer", "Index", "Admin")</li>
                    }
                    @if (User.IsInRole("UserGroupsViewer"))
                    {
                        <li>@Html.ActionLink("Gebruikersgroepen", "Index", "UserGroups")</li>
                    }
                    @if (User.IsInRole("RoleGroupsViewer"))
                    {
                        <li>@Html.ActionLink("Rolgroepen", "Index", "RoleGroups")</li>
                    }
                    @if (User.IsInRole("RolesViewer"))
                    {
                        <li>@Html.ActionLink("Rollen", "Index", "Roles")</li>
                    }
                </ul>
            </li>
        }
    </ul>
    @await Html.PartialAsync("_LoginPartial")
</div>